services:
  - type: web
    name: stallstarz
    env: node
    plan: free
    buildCommand: |
      npm install
      cd client
      npm install
      NODE_ENV=production node_modules/.bin/vite build
      cd ../server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_OPENCAGE_API_KEY
        sync: false
    domains:
      - stallstarz.onrender.com