services:
  - type: web
    name: stallstarz
    env: node
    plan: free
    buildCommand: |
      npm install
      cd client
      npm install
      npm install -D @types/react @types/react-dom typescript @vitejs/plugin-react
      npm run build
      cd ../server 
      npm install
      npm install -D @types/express @types/cors @types/jsonwebtoken @types/bcrypt typescript
      npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_OPENCAGE_API_KEY
        sync: false
    domains:
      - stallstarz.onrender.com